name: ci_pipline

on:
  push:
    - main

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - name: checkout github repository
      uses: actions/checkout@v4

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: rust fmt for code formating check
      run: cargo fmt --all -- --check

    - name: linting with clippy
      run: cargo clippy --all -targets --all-features -- -D warning

    - name: build rust application
      run: |
        cargo build --release

    - name: run unit and integration test
      run: |
        cargo test --all --all-features --verbose

    - name: run a security autdit test
      uses: actions-rs/audit-check@v1

    - name: check for unused dep in the code
      uses: cargo install cargo-udeps && udeps

    - name: Install Rust (Nightly) for performance Benchmarking
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly

    - name: Run Benchmarks
      run: cargo bench
