name: ci_pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust fmt for code formatting check
        run: cd zumo-project && cargo fmt --all -- --check

      - name: Linting with Clippy
        run: cd zumo-project && cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Rust application
        run: cd zumo-project && cargo build --release

      - name: Run unit and integration tests
        run: cd zumo-project && cargo test --all --all-features --verbose

      - name: Run a security audit test
        run: |
          cd zumo-project
          cargo generate-lockfile
          cargo audit
        env:
          CARGO_TERM_COLOR: always
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}

      - name: Install cargo-udeps
        run: cargo install cargo-udeps

      - name: Check for unused dependencies
        run: cd zumo-project && cargo udeps

      - name: Install Rust (Nightly) for performance benchmarking
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Run benchmarks
        run: cd zumo-project && cargo bench
