name: ci_pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust fmt for code formatting check
        run: cargo fmt --all -- --check

      - name: Linting with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Rust application
        run: cargo build --release

      - name: Run unit and integration tests
        run: cargo test --all --all-features --verbose

      - name: Run a security audit test
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets._GITHUB_TOKEN }}

      - name: Install cargo-udeps
        run: cargo install cargo-udeps

      - name: Check for unused dependencies
        run: cargo udeps

      - name: Install Rust (Nightly) for performance benchmarking
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Run benchmarks
        run: cargo bench
