name: ci_pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Cache Cargo Registry + Build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Cache Cargo bin
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-bin-${{ runner.os }}-

      - name: Install Rust (Stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust fmt for code formatting check
        run: cd zumo-project && cargo fmt --all -- --check

      - name: Linting with Clippy
        run: cd zumo-project && cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Rust application
        run: cd zumo-project && cargo build --release

      - name: Run unit and integration tests
        run: cd zumo-project && cargo test --all --all-features --verbose

      - name: Install cargo-audit
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          fi

      - name: Run a security audit test
        run: |
          cd zumo-project
          cargo generate-lockfile
          cargo audit
        env:
          CARGO_TERM_COLOR: always
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}

      - name: Install Rust (Nightly) for cargo-udeps
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly

      - name: Install cargo-udeps
        run: |
          if ! command -v cargo-udeps &> /dev/null; then
            cargo install cargo-udeps
          fi

      - name: Check for unused dependencies
        run: cd zumo-project && cargo udeps

      - name: Run benchmarks
        run: cd zumo-project && cargo bench

  build-and-scan-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build  the docker image
        run: |
          docker build -t captaingab/app:${{github.sha}} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "captaingab/app:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: push docker image to docker registry
        run: docker push captaingab/app:${{github.sha}}
